#!/usr/bin/env bash
# Run the fork's KUnit suites (core thunderbolt negotiation, tbnet, tbframe)
# for real via tools/testing/kunit/kunit.py against a v6.17 tree with the fork's
# drivers overlaid. The fleet/host kernels lack CONFIG_KUNIT, so this stands up a
# throwaway kunit kernel (x86_64 qemu, because USB4/INFINIBAND need PCI -> not UML).
# The tbrxe engine suite has its own runner (kernel/tbrxe/tests/run-kunit.sh).
#
# Usage:
#   drivers/thunderbolt_ibverbs/tools/run-kunit.sh [kunit.py filter args...]
#   KUNIT_TREE=/path/to/linux  drivers/thunderbolt_ibverbs/tools/run-kunit.sh
#   KUNIT_LOCKDEP=1            drivers/thunderbolt_ibverbs/tools/run-kunit.sh
#
# Examples:
#   ... run-kunit.sh                       # all suites
#   ... run-kunit.sh 'tbframe*'            # just the frame-service suites
#
# KUNIT_LOCKDEP=1 turns on the kernel's own locking validator (lockdep) for the
# run and uses a separate build dir so the fast default build is not clobbered.
# lockdep builds the lock dependency graph at runtime and splats on recursive
# acquisition, inverted (ABBA) ordering, irq-safe/irq-unsafe inversion and
# sleeping in atomic context. It only observes orderings the tests actually
# exercise, so a clean run is evidence about the exercised paths only. Any splat
# lands in the kunit.py output; grep the run for "WARNING", "BUG:",
# "possible recursive locking", "lock-inversion" or "INFO: possible".
set -euo pipefail

REPO="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
TREE="${KUNIT_TREE:-$HOME/Documents/linux-kunit}"
KVER="${KUNIT_KVER:-v6.17}"
LOCKDEP="${KUNIT_LOCKDEP:-0}"
if [[ "$LOCKDEP" == 1 ]]; then
	BUILD="$TREE/.kunit-tbv-lockdep"
else
	BUILD="$TREE/.kunit-tbv"
fi

if [[ ! -e "$TREE/tools/testing/kunit/kunit.py" ]]; then
	echo ">> cloning $KVER into $TREE (shallow)"
	git clone --depth 1 --branch "$KVER" \
		https://github.com/torvalds/linux.git "$TREE"
fi

echo ">> overlaying fork drivers onto $TREE"
rsync -a --delete --exclude='.git' "$REPO/drivers/thunderbolt/" "$TREE/drivers/thunderbolt/"
rsync -a --delete --exclude='.git' "$REPO/drivers/net/thunderbolt/" "$TREE/drivers/net/thunderbolt/"
# Patch the overlay's public header via the SAME shim the DKMS build uses, so
# the KUnit tree and the shipped package never drift on the header additions
# (completion.h, callback_xd/TB_PROTOCOL_HANDLER_HAS_XDOMAIN, domain_released).
# The shim reads <ksrc>/include/linux/thunderbolt.h and writes <out>/linux/;
# here ksrc == the overlay tree, and we copy the result back in place.
# Restore the pristine upstream header first: a previous run overwrote it
# with the shimmed copy, and the shim's idempotency grep would then keep
# whatever (possibly stale) layout that old copy carries instead of applying
# the current one.
git -C "$TREE" checkout -- include/linux/thunderbolt.h
HDR_GEN="$(mktemp -d)"
"$REPO/dkms/tbfix-gen-thunderbolt-header.sh" "$TREE" "$HDR_GEN"
cp "$HDR_GEN/linux/thunderbolt.h" "$TREE/include/linux/thunderbolt.h"
rm -rf "$HDR_GEN"
mkdir -p "$TREE/drivers/thunderbolt_ibverbs/kernel" "$TREE/drivers/thunderbolt_ibverbs/proto"
rsync -a --delete \
	--exclude='*.o' --exclude='*.ko' --exclude='*.mod*' --exclude='.*.cmd' \
	--exclude='Module.symvers' --exclude='modules.order' \
	"$REPO/drivers/thunderbolt_ibverbs/kernel/" "$TREE/drivers/thunderbolt_ibverbs/kernel/"
rsync -a --delete "$REPO/drivers/thunderbolt_ibverbs/proto/" "$TREE/drivers/thunderbolt_ibverbs/proto/"

# Single source of truth: derive the object + test lists for the tbframe
# module from the repo's kernel/tbframe/Makefile (the DKMS build) so they
# never drift from this overlay.
TBF_MK="$REPO/drivers/thunderbolt_ibverbs/kernel/tbframe/Makefile"
xformf() { tr ' \t\\' '\n\n\n' | sed -e '/^$/d' \
	-e 's#^tests/#kernel/tbframe/tests/#;t' -e 's#^#kernel/tbframe/#' \
	| tr '\n' ' '; }
TBF_Y=$(sed -n 's/^tbframe-y *:= *//p' "$TBF_MK" | xformf)
TBF_K=$(sed -n 's/^tbframe-\$(CONFIG_KUNIT) *+= *//p' "$TBF_MK" | xformf)

cat > "$TREE/drivers/thunderbolt_ibverbs/Makefile" <<MK
# SPDX-License-Identifier: GPL-2.0  (generated by run-kunit.sh from kernel/tbframe/Makefile)
obj-\$(CONFIG_THUNDERBOLT_IBVERBS) += tbframe.o
tbframe-y := $TBF_Y
tbframe-\$(CONFIG_KUNIT) += $TBF_K
ccflags-y := -I\$(src)/kernel -I\$(src) -DDEBUG -Wno-unused-parameter
MK

cat > "$TREE/drivers/thunderbolt_ibverbs/Kconfig" <<'KC'
# SPDX-License-Identifier: GPL-2.0  (generated by run-kunit.sh)
config THUNDERBOLT_IBVERBS
	tristate "Thunderbolt ibverbs RDMA transport (KUnit)"
	depends on USB4 && INFINIBAND && CONFIGFS_FS
KC

grep -q 'thunderbolt_ibverbs/Kconfig' "$TREE/drivers/Kconfig" || \
	sed -i 's#source "drivers/thunderbolt/Kconfig"#source "drivers/thunderbolt/Kconfig"\nsource "drivers/thunderbolt_ibverbs/Kconfig"#' "$TREE/drivers/Kconfig"
grep -q 'thunderbolt_ibverbs/' "$TREE/drivers/Makefile" || \
	printf 'obj-$(CONFIG_THUNDERBOLT_IBVERBS) += thunderbolt_ibverbs/\n' >> "$TREE/drivers/Makefile"

mkdir -p "$BUILD"
cat > "$BUILD/.kunitconfig" <<'CFG'
CONFIG_KUNIT=y
CONFIG_PCI=y
CONFIG_USB4=y
CONFIG_USB4_KUNIT_TEST=y
CONFIG_USB4_NET=y
CONFIG_USB4_NET_KUNIT_TEST=y
CONFIG_NET=y
CONFIG_INET=y
CONFIG_NETDEVICES=y
CONFIG_IPV6=y
CONFIG_INFINIBAND=y
CONFIG_INFINIBAND_USER_ACCESS=y
CONFIG_CONFIGFS_FS=y
CONFIG_THUNDERBOLT_IBVERBS=y
CFG

if [[ "$LOCKDEP" == 1 ]]; then
	cat >> "$BUILD/.kunitconfig" <<'CFG'
CONFIG_DEBUG_KERNEL=y
CONFIG_LOCKDEP=y
CONFIG_PROVE_LOCKING=y
CONFIG_DEBUG_LOCK_ALLOC=y
CONFIG_DEBUG_SPINLOCK=y
CONFIG_DEBUG_MUTEXES=y
CONFIG_DEBUG_RT_MUTEXES=y
CONFIG_DEBUG_RWSEMS=y
CONFIG_DEBUG_ATOMIC_SLEEP=y
CONFIG_DEBUG_LOCKDEP=y
CONFIG_LOCK_STAT=y
CONFIG_STACKTRACE=y
CFG
	echo ">> lockdep enabled (build dir $BUILD)"
fi

echo ">> running kunit.py (x86_64 qemu)"
exec "$TREE/tools/testing/kunit/kunit.py" run \
	--arch=x86_64 --kunitconfig="$BUILD" --build_dir="$BUILD" "$@"
