#!/usr/bin/env bash
# Run the fork's KUnit suites (core thunderbolt negotiation + thunderbolt_ibverbs)
# for real via tools/testing/kunit/kunit.py against a v6.17 tree with the fork's
# drivers overlaid. The fleet/host kernels lack CONFIG_KUNIT, so this stands up a
# throwaway kunit kernel (x86_64 qemu, because USB4/INFINIBAND need PCI -> not UML).
#
# Usage:
#   drivers/thunderbolt_ibverbs/tools/run-kunit.sh [kunit.py filter args...]
#   KUNIT_TREE=/path/to/linux  drivers/thunderbolt_ibverbs/tools/run-kunit.sh
#
# Examples:
#   ... run-kunit.sh                       # all suites
#   ... run-kunit.sh 'tbv_rail_mac'        # just the per-rail MAC suite
#   ... run-kunit.sh 'thunderbolt_ibverbs*'
set -euo pipefail

REPO="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
TREE="${KUNIT_TREE:-$HOME/Documents/linux-kunit}"
KVER="${KUNIT_KVER:-v6.17}"
BUILD="$TREE/.kunit-tbv"

if [[ ! -e "$TREE/tools/testing/kunit/kunit.py" ]]; then
	echo ">> cloning $KVER into $TREE (shallow)"
	git clone --depth 1 --branch "$KVER" \
		https://github.com/torvalds/linux.git "$TREE"
fi

echo ">> overlaying fork drivers onto $TREE"
rsync -a --delete --exclude='.git' "$REPO/drivers/thunderbolt/" "$TREE/drivers/thunderbolt/"
rsync -a --delete --exclude='.git' "$REPO/drivers/net/thunderbolt/" "$TREE/drivers/net/thunderbolt/"
# Patch the overlay's public header via the SAME shim the DKMS build uses, so
# the KUnit tree and the shipped package never drift on the header additions
# (completion.h, callback_xd/TB_PROTOCOL_HANDLER_HAS_XDOMAIN, domain_released).
# The shim reads <ksrc>/include/linux/thunderbolt.h and writes <out>/linux/;
# here ksrc == the overlay tree, and we copy the result back in place.
HDR_GEN="$(mktemp -d)"
"$REPO/dkms/tbfix-gen-thunderbolt-header.sh" "$TREE" "$HDR_GEN"
cp "$HDR_GEN/linux/thunderbolt.h" "$TREE/include/linux/thunderbolt.h"
rm -rf "$HDR_GEN"
mkdir -p "$TREE/drivers/thunderbolt_ibverbs/kernel" "$TREE/drivers/thunderbolt_ibverbs/proto"
rsync -a --delete \
	--exclude='*.o' --exclude='*.ko' --exclude='*.mod*' --exclude='.*.cmd' \
	--exclude='Module.symvers' --exclude='modules.order' \
	"$REPO/drivers/thunderbolt_ibverbs/kernel/" "$TREE/drivers/thunderbolt_ibverbs/kernel/"
rsync -a --delete "$REPO/drivers/thunderbolt_ibverbs/proto/" "$TREE/drivers/thunderbolt_ibverbs/proto/"

# Single source of truth: derive the object + test lists from the repo's
# kernel/Makefile (the DKMS build) so they never drift from this overlay.
# Path-adjust for the in-tree layout (module dir holds kernel/ and proto/):
# bare/tests -> kernel/...,  ../proto/ -> proto/.
SRC_MK="$REPO/drivers/thunderbolt_ibverbs/kernel/Makefile"
xform() { tr ' \t\\' '\n\n\n' | sed -e '/^$/d' \
	-e 's#^\.\./proto/#proto/#;t' -e 's#^tests/#kernel/tests/#;t' -e 's#^#kernel/#' \
	| tr '\n' ' '; }
Y_OBJS=$(sed -n 's/^thunderbolt_ibverbs-y *:= *//p' "$SRC_MK" | xform)
K_OBJS=$(sed -n 's/^thunderbolt_ibverbs-\$(CONFIG_KUNIT) *+= *//p' "$SRC_MK" | xform)

cat > "$TREE/drivers/thunderbolt_ibverbs/Makefile" <<MK
# SPDX-License-Identifier: GPL-2.0  (generated by run-kunit.sh from kernel/Makefile)
obj-\$(CONFIG_THUNDERBOLT_IBVERBS) += thunderbolt_ibverbs.o
thunderbolt_ibverbs-y := $Y_OBJS
thunderbolt_ibverbs-\$(CONFIG_KUNIT) += $K_OBJS
ccflags-y := -I\$(src)/kernel -I\$(src) -DDEBUG -Wno-unused-parameter
MK

cat > "$TREE/drivers/thunderbolt_ibverbs/Kconfig" <<'KC'
# SPDX-License-Identifier: GPL-2.0  (generated by run-kunit.sh)
config THUNDERBOLT_IBVERBS
	tristate "Thunderbolt ibverbs RDMA transport (KUnit)"
	depends on USB4 && INFINIBAND && CONFIGFS_FS
KC

grep -q 'thunderbolt_ibverbs/Kconfig' "$TREE/drivers/Kconfig" || \
	sed -i 's#source "drivers/thunderbolt/Kconfig"#source "drivers/thunderbolt/Kconfig"\nsource "drivers/thunderbolt_ibverbs/Kconfig"#' "$TREE/drivers/Kconfig"
grep -q 'thunderbolt_ibverbs/' "$TREE/drivers/Makefile" || \
	printf 'obj-$(CONFIG_THUNDERBOLT_IBVERBS) += thunderbolt_ibverbs/\n' >> "$TREE/drivers/Makefile"

mkdir -p "$BUILD"
cat > "$BUILD/.kunitconfig" <<'CFG'
CONFIG_KUNIT=y
CONFIG_PCI=y
CONFIG_USB4=y
CONFIG_USB4_KUNIT_TEST=y
CONFIG_NET=y
CONFIG_INET=y
CONFIG_IPV6=y
CONFIG_INFINIBAND=y
CONFIG_INFINIBAND_USER_ACCESS=y
CONFIG_CONFIGFS_FS=y
CONFIG_THUNDERBOLT_IBVERBS=y
CFG

echo ">> running kunit.py (x86_64 qemu)"
exec "$TREE/tools/testing/kunit/kunit.py" run \
	--arch=x86_64 --kunitconfig="$BUILD" --build_dir="$BUILD" "$@"
