#!/usr/bin/env bash
# Run the thunderbolt_frame_rxe KUnit suite for real via
# tools/testing/kunit/kunit.py against a v6.17 tree with rxe/ (and the frame
# contract header) overlaid. Modeled on
# drivers/thunderbolt_frame/tools/run-kunit.sh: the fleet/host kernels lack
# CONFIG_KUNIT, so this stands up a throwaway kunit kernel (x86_64 qemu;
# INFINIBAND wants PCI -> not UML).
#
# Usage:
#   drivers/thunderbolt_frame/rxe/tests/run-kunit.sh [filter...]
#   KUNIT_TREE=/path/to/linux ... tests/run-kunit.sh
#
# The overlay preserves the source layout (rxe/ next to frame/) so the
# '#include "../frame/tbframe.h"' contract reference resolves unchanged.
# tbrxe_tbframe_glue.c is excluded by the Makefile under CONFIG_KUNIT; the
# test installs mock transport ops instead.
set -euo pipefail

REPO="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
SRC="$REPO/drivers/thunderbolt_frame"
TREE="${KUNIT_TREE:-$HOME/Documents/linux-kunit}"
KVER="${KUNIT_KVER:-v6.17}"
BUILD="$TREE/.kunit-tbrxe"

if [[ ! -e "$TREE/tools/testing/kunit/kunit.py" ]]; then
	echo ">> cloning $KVER into $TREE (shallow)"
	git clone --depth 1 --branch "$KVER" \
		https://github.com/torvalds/linux.git "$TREE"
fi

echo ">> overlaying rxe/ + frame/ onto $TREE"
# Drop scaffold wiring left by pre-rename runs (their Kconfig source line
# points at a directory this overlay no longer creates).
rm -rf "$TREE/drivers/tbrxe_scaffold/tbrxe"
sed -i '\#tbrxe_scaffold/tbrxe#d' "$TREE/drivers/Kconfig" "$TREE/drivers/Makefile"
mkdir -p "$TREE/drivers/tbrxe_scaffold"
rsync -a --delete \
	--exclude='*.o' --exclude='*.ko' --exclude='*.mod*' --exclude='.*.cmd' \
	--exclude='Module.symvers' --exclude='modules.order' \
	"$SRC/rxe/" "$TREE/drivers/tbrxe_scaffold/rxe/"
rsync -a --delete \
	--exclude='*.o' --exclude='*.ko' --exclude='*.mod*' --exclude='.*.cmd' \
	--exclude='Module.symvers' --exclude='modules.order' \
	"$SRC/frame/" "$TREE/drivers/tbrxe_scaffold/frame/"

# Single source of truth: derive the object lists from the out-of-tree
# Makefile so the overlay never drifts from the DKMS-style build.
SRC_MK="$SRC/rxe/Makefile"
xform() { tr ' \t\\' '\n\n\n' | sed '/^$/d' | tr '\n' ' '; }
Y_OBJS=$(sed -n '/^thunderbolt_frame_rxe-y :=/,/[^\\]$/p' "$SRC_MK" | sed 's/^thunderbolt_frame_rxe-y := //' | xform)
ODP_OBJS=$(sed -n 's/^thunderbolt_frame_rxe-\$(CONFIG_INFINIBAND_ON_DEMAND_PAGING) += //p' "$SRC_MK" | xform)
K_OBJS=$(sed -n 's/^thunderbolt_frame_rxe-\$(CONFIG_KUNIT) += //p' "$SRC_MK" | xform)
# The glue is a no-CONFIG_KUNIT object; drop it from the overlay build.
Y_OBJS=${Y_OBJS//tbrxe_tbframe_glue.o/}

cat > "$TREE/drivers/tbrxe_scaffold/rxe/Makefile" <<MK
# SPDX-License-Identifier: GPL-2.0  (generated by tests/run-kunit.sh)
obj-\$(CONFIG_RDMA_THUNDERBOLT_FRAME_RXE) += thunderbolt_frame_rxe.o
thunderbolt_frame_rxe-y := $Y_OBJS
thunderbolt_frame_rxe-\$(CONFIG_INFINIBAND_ON_DEMAND_PAGING) += $ODP_OBJS
thunderbolt_frame_rxe-\$(CONFIG_KUNIT) += $K_OBJS
ccflags-y := -Wall -Wextra -Wno-unused-parameter -DDEBUG -I\$(src)
MK

grep -q 'tbrxe_scaffold/rxe/Kconfig' "$TREE/drivers/Kconfig" || \
	sed -i 's#source "drivers/infiniband/Kconfig"#source "drivers/infiniband/Kconfig"\nsource "drivers/tbrxe_scaffold/rxe/Kconfig"#' "$TREE/drivers/Kconfig"
grep -q 'tbrxe_scaffold' "$TREE/drivers/Makefile" || \
	printf 'obj-$(CONFIG_RDMA_THUNDERBOLT_FRAME_RXE) += tbrxe_scaffold/rxe/\n' >> "$TREE/drivers/Makefile"

mkdir -p "$BUILD"
cat > "$BUILD/.kunitconfig" <<'CFG'
CONFIG_KUNIT=y
CONFIG_PCI=y
CONFIG_NET=y
CONFIG_INET=y
CONFIG_IPV6=y
CONFIG_INFINIBAND=y
CONFIG_RDMA_THUNDERBOLT_FRAME_RXE=y
CFG

echo ">> running kunit.py (x86_64 qemu)"
exec "$TREE/tools/testing/kunit/kunit.py" run \
	--arch=x86_64 --kunitconfig="$BUILD" --build_dir="$BUILD" \
	"${@:-tbrxe*}"
